# Change these first
owner: revinet-status # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

# Order of sites: Main Page/ReviPhab above anything else, then ABC order, then legacy sites.
sites:
  - name: Main Page
    url: https://revi.xyz/
  - name: ReviPhab
    url: https://stuff.revi.xyz/status/
  - name: Basecamp
    url: $BASECAMP_URL
    icon: https://basecamp.com/favicon.ico 
  - name: Blog (by omg.lol)
    url: https://revi.blog/P86
  - name: Fastmail
    url: https://app.fastmail.com/
  - name: Firefly 3
    url: https://ff3.revi.xyz/login
  - name: git.silicon.moe
    url: https://git.silicon.moe/revi/todo/-/issues/4
  - name: GnuPG Key Repository
    url: https://k.revi.xyz/0xBEFF197A.asc
    icon: https://static.miraheze.org/reviwiki/0/09/Reviwikifavicon.ico
  - name: Google Calendar RSVP
    url: $GOOGLECAL_URL
    icon: https://workspace.google.com/favicon.ico
  - name: Listed.To (note distributor)
    url: https://listed.to/p/wrEd7iVigI
  - name: Migadu
    url: https://admin.migadu.com/public/login 
  - name: Postmark
    url: https://api.postmarkapp.com/senders?count=50&offset=0
    icon: https://postmarkapp.com/images/favicon.ico
    headers:
      - "Accept: application/json"
      - "X-Postmark-Account-Token: $POSTMARK_TOKEN"
  - name: Old Sharlayan
    url: https://old.sharlayan.city/nodeinfo/2.0
  - name: PasteBin (by omg.lol)
    url: https://paste.revi.xyz/temp20230711-1/raw
  - name: Todoist
    url: https://app.todoist.com/auth/login 
  - name: Traccar
    url: https://traccar.revi.xyz/
  - name: URL Shortener (by omg.lol)
    url: https://revi.kr/discord/wut
  - name: Wiki (by Miraheze)
    url: https://revi.wiki/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=json
  - name: Old Blog (by Tistory)
    url: https://tistory.revi.blog/
  - name: ShinhanCard
    url: https://www.shinhancard.com/
  - name: HyundaiCard
    url: https://www.hyundaicard.com/


assignees:
  - revi

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.revi.me
  # baseUrl: /your-repo-name
  logoUrl: https://r2-cdn.revicdn.net/pfp2.png
  name: reviNet Status (Powered by Upptime)
  introTitle: "ReviNet Status Page"
  introMessage: "[Upptime](https://github.com/upptime/upptime)으로 제공되는 서버 상태 페이지입니다."
  navbar:
    - title: ReviNet
      href: https://revi.xyz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  customHeadHtml: "<meta name=\"robots\" content=\"noindex\">"

commitMessages:
  commitAuthorName: "revibot"
  commitAuthorEmail: "github-revibot@revi.kr"

workflowSchedule:
  graphs: "0 3,9,15,21 * * *"
  responseTime: "0 */6 * * *"
  staticSite: "0 17 * * 1"
  summary: "59 */6 * * *"
  updateTemplate: "0 15 * * 1"
  updates: "0 20 * * *"
  uptime: "*/5 * * * *"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

user-agent: upptime(@revinet-status, v2023-09-09)/ contact https://github.com/revi for issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
